# Generated by Django 6.0 on 2025-12-14 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocknet', '0002_user_wallet_address_course_assignment_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role__rolename': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to='blocknet.user'),
        ),
    ]
