# Generated by Django 6.0 on 2025-12-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocknet', '0003_alter_course_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role__rolename': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='blocknet.user'),
        ),
    ]
