# Generated by Django 6.0 on 2025-12-15 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocknet', '0004_alter_courseenrollment_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='blockchain_transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__rolename__in': ['professor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='blocknet.user'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'role__rolename': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments_created', to='blocknet.user'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='blockchain_transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role__rolename': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='blocknet.user'),
        ),
    ]
