# Generated by Django 5.2.9 on 2025-12-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocknet', '0006_alter_announcement_id_alter_assignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='blockchain_assignment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='blockchain_result_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='blockchain_submission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='blockchain_transaction_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethereum_address', models.CharField(max_length=42)),
                ('encrypted_private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='blocknet.user')),
            ],
        ),
    ]
