# Generated by Django 5.2.9 on 2025-12-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocknet', '0007_assignment_blockchain_assignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blockchain_profile_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
